spring:
  application:
    name: gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:



        # ==============================
        # USER SERVICE
        # ==============================

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - UserRouteFilter


        # ==============================
        # POLICY SERVICE
        # ==============================

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/policies/**


        # ==============================
        # CLAIM SERVICE
        # ==============================

        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/claims/**
          filters:

            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY
                method: GET

            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

            - name: CircuitBreaker
              args:
                name: claimServiceCircuitBreaker
                fallbackUri: forward:/fallback/claims


        # ==============================
        # PAYMENT SERVICE
        # ==============================

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**


# =====================================================
# RESILIENCE4J
# =====================================================

resilience4j:

  circuitbreaker:
    instances:
      claimServiceCircuitBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

  timelimiter:
    instances:
      claimServiceCircuitBreaker:
        timeout-duration: 3s

  bulkhead:
    instances:
      claimServiceBulkhead:
        maxConcurrentCalls: 2
        maxWaitDuration: 0ms


# =====================================================
# MANAGEMENT / OBSERVABILITY
# =====================================================

management:

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    enabled: true
    sampling:
      probability: 1.0


  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true


# =====================================================
# SERVER
# =====================================================

server:
  port: 8080


# =====================================================
# EUREKA
# =====================================================

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/


# =====================================================
# LOGGING
# =====================================================

logging:

  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "

  include-application-name: false

  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: TRACE
    org.springframework.cloud.gateway.filter.factory.RequestRateLimiterGatewayFilterFactory: DEBUG


#spring:
#  application:
#    name: gateway
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#  cloud:
#    gateway:
#      routes:
#
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#          filters:
#            - UserRouteFilter
#
#
#        - id: policy-service
#          uri: lb://policy-service
#          predicates:
#            - Path=/policies/**
#
#
#        - id: claim-service
#          uri: lb://claim-service
#          predicates:
#              - Path=/claims/**
#          filters:
#
#            - name: Retry
#              args:
#                retries: 2
#                statuses: BAD_GATEWAY
#                method: GET
#
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter.replenishRate: 5
#                redis-rate-limiter.burstCapacity: 10
#
#
#            - name: CircuitBreaker
#              args:
#                name: claimServiceCircuitBreaker
#                fallbackUri: forward:/fallback/claims
#
#
#        - id: payment-service
#          uri: lb://payment-service
#          predicates:
#            - Path=/payments/**
#
#
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      claimServiceCircuitBreaker:
#        sliding-window-size: 5
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 10s
#        permitted-number-of-calls-in-half-open-state: 2
#
#  timelimiter:
#    instances:
#      claimServiceCircuitBreaker:
#        timeout-duration: 3s
#
#
#  bulkhead:
#    instances:
#      claimServiceBulkhead:
#        maxConcurrentCalls: 2
#        maxWaitDuration: 0ms
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#
#  tracing:
#    sampling:
#      probability: 1.0
#
#  otlp:
#    tracing:
#      endpoint: http://jaeger:4318/v1/traces
#
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http.server.requests: true
#
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://discovery-service:8761/eureka/
#
## ==============================
## DISTRIBUTED TRACING
## ==============================
#
#
#logging:
#  level:
#    org.springframework.data.redis: DEBUG
#    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
#    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: TRACE
#    org.springframework.cloud.gateway.filter.factory.RequestRateLimiterGatewayFilterFactory: DEBUG
#
